# Generated by Django 5.0.6 on 2024-11-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutExpressions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_expression', models.CharField(max_length=100)),
                ('user_ans', models.CharField(max_length=50)),
                ('points_for_solve', models.IntegerField(default=1)),
                ('user_eps', models.FloatField(blank=True, default=0.0)),
                ('user_type', models.CharField(blank=True, default='float', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AboutTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tests', models.CharField(max_length=255)),
                ('time_to_solution', models.CharField(default='90', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('name_slug_tests', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('expressions', models.ManyToManyField(to='create_tests.aboutexpressions')),
            ],
        ),
    ]
