# Generated by Django 5.0.6 on 2025-03-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutexpressions',
            name='true_ans',
            field=models.CharField(default='1', max_length=15),
        ),
        migrations.AlterField(
            model_name='aboutexpressions',
            name='user_ans',
            field=models.CharField(max_length=150),
        ),
    ]
