# Generated by Django 5.0.6 on 2025-03-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0002_aboutexpressions_true_ans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutexpressions',
            name='user_eps',
            field=models.CharField(blank=True, default='0', max_length=150),
        ),
    ]
