# Generated by Django 5.0.6 on 2025-03-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0003_alter_aboutexpressions_user_eps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutexpressions',
            name='true_ans',
            field=models.CharField(max_length=15),
        ),
    ]
