# Generated by Django 5.0.6 on 2025-03-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0005_alter_aboutexpressions_true_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutexpressions',
            name='options',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
