# Generated by Django 5.0.6 on 2025-05-04 16:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0007_remove_aboutexpressions_options_and_more'),
        ('users', '0010_alter_studentinstitute_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Другое', max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutexpressions',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='abouttest',
            name='is_published',
        ),
        migrations.AddField(
            model_name='abouttest',
            name='description',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='abouttest',
            name='num_of_attempts',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='abouttest',
            name='type_of_result',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='abouttest',
            name='time_to_solution',
            field=models.DurationField(default=datetime.timedelta(seconds=5400)),
        ),
        migrations.CreateModel(
            name='PublishedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.studentgroup')),
                ('test_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='create_tests.abouttest')),
            ],
        ),
        migrations.AddField(
            model_name='abouttest',
            name='subj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='create_tests.subjects'),
        ),
    ]
