# Generated by Django 5.0.6 on 2025-04-23 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0007_remove_aboutexpressions_options_and_more'),
        ('users', '0006_remove_studentdata_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abouttest',
            name='is_published',
        ),
        migrations.AddField(
            model_name='abouttest',
            name='num_of_attempts',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='abouttest',
            name='type_of_result',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.CreateModel(
            name='PublishedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.studentgroup')),
                ('test_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='create_tests.abouttest')),
            ],
        ),
    ]
