# Generated by Django 5.0.6 on 2025-05-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0008_subjects_remove_aboutexpressions_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttest',
            name='is_done',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='abouttest',
            name='is_published',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
