# Generated by Django 5.0.6 on 2025-05-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0009_abouttest_is_done_abouttest_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttest',
            name='is_done',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='abouttest',
            name='is_published',
            field=models.IntegerField(default=0),
        ),
    ]
