# Generated by Django 5.0.6 on 2025-05-10 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0010_alter_abouttest_is_done_alter_abouttest_is_published'),
        ('users', '0010_alter_studentinstitute_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedgroup',
            name='is_published',
        ),
        migrations.AddField(
            model_name='publishedgroup',
            name='teacher_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.teacherdata'),
            preserve_default=False,
        ),
    ]
