# Generated by Django 5.0.6 on 2025-05-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0011_remove_publishedgroup_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutexpressions',
            name='user_type',
            field=models.CharField(blank=True, default='float', max_length=150),
        ),
    ]
