# Generated by Django 5.0.6 on 2025-05-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0012_aboutexpressions_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttest',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
