# Generated by Django 5.0.6 on 2025-05-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0013_alter_abouttest_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttest',
            name='is_published',
            field=models.IntegerField(default=0),
        ),
    ]
