# Generated by Django 5.0.6 on 2025-06-11 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0014_alter_abouttest_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.IntegerField(choices=[(1, 'Целые'), (2, 'Нецелые'), (3, 'Строки')], unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='aboutexpressions',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='create_tests.typeanswer'),
        ),
    ]
