# Generated by Django 5.0.6 on 2025-06-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0015_typeanswer_alter_aboutexpressions_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttest',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
