# Generated by Django 5.0.6 on 2025-06-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0016_abouttest_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abouttest',
            name='is_done',
        ),
    ]
