# Generated by Django 5.0.6 on 2025-06-13 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0016_abouttest_is_draft'),
        ('users', '0012_teacherdata_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttest',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_tests', to='users.teacherdata'),
        ),
    ]
