# Generated by Django 5.0.6 on 2025-09-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0017_abouttest_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeanswer',
            name='type_code',
            field=models.IntegerField(choices=[(1, 'Целые'), (2, 'Нецелые'), (3, 'Строки'), (4, 'Матрицы')], unique=True),
        ),
    ]
