# Generated by Django 5.0.6 on 2025-09-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0018_alter_typeanswer_type_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeanswer',
            name='type_code',
            field=models.IntegerField(choices=[(1, 'Целые'), (2, 'Нецелые'), (4, 'Матрицы')], unique=True),
        ),
    ]
