# Generated by Django 5.0.6 on 2025-09-23 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0019_alter_typeanswer_type_code'),
    ]

    operations = [
    ]
