# Generated by Django 5.0.6 on 2025-09-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0020_auto_20250924_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.IntegerField(choices=[(1, 'Евклидова норма'), (2, 'Первая норма'), (3, 'Бесконечная норма')], unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='typeanswer',
            name='type_code',
            field=models.IntegerField(choices=[(1, 'Целые'), (2, 'Нецелые'), (3, 'Строки'), (4, 'Матрицы')], unique=True),
        ),
    ]
