# Generated by Django 5.0.6 on 2025-09-28 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0021_typenorm_alter_typeanswer_type_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutexpressions',
            name='matrix_norms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='create_tests.typenorm'),
        ),
    ]
