# Generated by Django 5.0.6 on 2025-09-30 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0022_aboutexpressions_matrix_norms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutexpressions',
            name='matrix_norms',
        ),
        migrations.CreateModel(
            name='TypeNormForMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_norms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='create_tests.typenorm')),
                ('num_expr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_tests.aboutexpressions')),
            ],
        ),
    ]
