# Generated by Django 5.0.6 on 2025-10-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0023_remove_aboutexpressions_matrix_norms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutexpressions',
            name='block_expression_num',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='aboutexpressions',
            name='number',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
