# Generated by Django 5.0.6 on 2025-10-14 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0024_aboutexpressions_block_expression_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('points_for_solve', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='abouttest',
            name='task_groups',
            field=models.ManyToManyField(blank=True, to='create_tests.taskgroup'),
        ),
        migrations.CreateModel(
            name='TaskVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_expression', models.CharField(max_length=100)),
                ('user_ans', models.CharField(max_length=150)),
                ('true_ans', models.CharField(default='1', max_length=15)),
                ('user_eps', models.CharField(blank=True, default='0', max_length=150)),
                ('exist_select', models.BooleanField(default=False)),
                ('task_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='create_tests.taskgroup')),
                ('user_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='create_tests.typeanswer')),
            ],
        ),
        migrations.CreateModel(
            name='TypeNormForTaskVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_norms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='create_tests.typenorm')),
                ('task_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_tests.taskvariant')),
            ],
        ),
    ]
