# Generated by Django 5.0.6 on 2025-11-04 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0025_taskgroup_abouttest_task_groups_taskvariant_and_more'),
        ('users', '0015_studentgroup_course_studentgroup_education_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название списка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('groups', models.ManyToManyField(to='users.studentgroup', verbose_name='Группы')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacherdata', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Список групп для публикации',
                'verbose_name_plural': 'Списки групп для публикации',
                'ordering': ['-created_at'],
            },
        ),
    ]
