# Generated by Django 5.0.6 on 2026-01-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0027_abouttest_result_display_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttest',
            name='grade_3_threshold',
            field=models.IntegerField(default=35, help_text='Минимальный процент для оценки 3'),
        ),
        migrations.AddField(
            model_name='abouttest',
            name='grade_4_threshold',
            field=models.IntegerField(default=60, help_text='Минимальный процент для оценки 4'),
        ),
        migrations.AddField(
            model_name='abouttest',
            name='grade_5_threshold',
            field=models.IntegerField(default=80, help_text='Минимальный процент для оценки 5'),
        ),
        migrations.AlterField(
            model_name='abouttest',
            name='result_display_mode',
            field=models.CharField(choices=[('only_score', 'Только баллы'), ('show_correct', 'Показывать правильные ответы')], default='only_score', max_length=20),
        ),
    ]
