# Generated by Django 5.0.6 on 2026-03-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0028_abouttest_grade_3_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutexpressions',
            name='block_expression_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aboutexpressions',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
