# Generated by Django 6.0.2 on 2026-03-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0032_merge_number_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeanswer',
            name='type_code',
            field=models.IntegerField(choices=[(1, 'Число'), (3, 'Строки'), (4, 'Матрицы'), (5, 'Свободный ответ')], unique=True),
        ),
    ]
