# Generated by Django 5.0.6 on 2026-09-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0033_alter_typeanswer_type_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutexpressions',
            name='user_expression',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='taskvariant',
            name='user_expression',
            field=models.TextField(),
        ),
    ]
