# Generated by Django 5.0.6 on 2026-09-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0034_alter_aboutexpressions_user_expression_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutexpressions',
            name='true_ans',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='taskvariant',
            name='true_ans',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
