# Generated by Django 5.0.6 on 2026-09-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0035_alter_aboutexpressions_true_ans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutexpressions',
            name='true_ans',
            field=models.TextField(default='1'),
        ),
        migrations.AlterField(
            model_name='aboutexpressions',
            name='user_ans',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutexpressions',
            name='user_eps',
            field=models.TextField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='taskvariant',
            name='true_ans',
            field=models.TextField(default='1'),
        ),
        migrations.AlterField(
            model_name='taskvariant',
            name='user_ans',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='taskvariant',
            name='user_eps',
            field=models.TextField(blank=True, default='0'),
        ),
    ]
