# Generated by Django 5.0.6 on 2025-04-23 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_studentgroup_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.studentdepartment'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.studentdirection'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.studentinstitute'),
        ),
    ]
