# Generated by Django 5.0.6 on 2025-04-23 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_studentdepartment_studentdirection_studentinstitute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='department',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='direction',
        ),
        migrations.DeleteModel(
            name='StudentDepartment',
        ),
        migrations.DeleteModel(
            name='StudentDirection',
        ),
    ]
