# Generated by Django 5.0.6 on 2025-04-24 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_studentgroup_name_inst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='name_inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.studentinstitute'),
        ),
    ]
