# Generated by Django 5.0.6 on 2025-05-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_studentdata_count_solve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinstitute',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
