# Generated by Django 5.0.6 on 2025-05-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_studentinstitute_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whitelist',
            old_name='teacherMail',
            new_name='teacher_mail',
        ),
    ]
