# Generated by Django 5.0.6 on 2025-06-11 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_teachermail_whitelist_teacher_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdata',
            name='institute',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='users.studentinstitute'),
        ),
    ]
