# Generated by Django 5.0.6 on 2025-10-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_teacherdata_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
        migrations.AddField(
            model_name='teacherdata',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
