# Generated by Django 5.0.6 on 2025-11-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='course',
            field=models.IntegerField(choices=[(1, '1 курс'), (2, '2 курс'), (3, '3 курс'), (4, '4 курс')], default=1),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='education_level',
            field=models.CharField(choices=[('bachelor', 'Бакалавриат'), ('master', 'Магистратура')], default='bachelor', max_length=8),
        ),
    ]
