# Generated by Django 5.0.6 on 2024-11-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('create_tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(max_length=255)),
                ('resAnswer', models.CharField(blank=True, max_length=255)),
                ('teacherExpressions', models.ManyToManyField(to='create_tests.aboutexpressions')),
            ],
        ),
    ]
