# Generated by Django 5.0.6 on 2025-03-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solving_tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='resAnswer',
            new_name='allResAnswer',
        ),
        migrations.RenameField(
            model_name='studentresult',
            old_name='accuracy',
            new_name='resultPoints',
        ),
    ]
