# Generated by Django 5.0.6 on 2025-05-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solving_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='delete_after',
            field=models.IntegerField(default=1),
        ),
    ]
