# Generated by Django 5.0.6 on 2025-11-10 20:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_tests', '0027_abouttest_result_display_mode'),
        ('solving_tests', '0003_rename_resanswer_studentresult_res_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentresult',
            options={'ordering': ['-completed_at', '-started_at']},
        ),
        migrations.AddField(
            model_name='studentresult',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='max_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='percentage_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='teacher_expressions',
            field=models.ManyToManyField(blank=True, to='create_tests.aboutexpressions'),
        ),
        migrations.CreateModel(
            name='StudentTaskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.CharField(blank=True, max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.FloatField(default=0)),
                ('max_points', models.FloatField(default=0)),
                ('expression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create_tests.aboutexpressions')),
                ('student_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_answers', to='solving_tests.studentresult')),
                ('task_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create_tests.taskvariant')),
            ],
            options={
                'indexes': [models.Index(fields=['student_result', 'task_variant'], name='solving_tes_student_353fea_idx'), models.Index(fields=['student_result', 'expression'], name='solving_tes_student_12d181_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentTaskGroupResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.FloatField(default=0)),
                ('max_points', models.FloatField(default=0)),
                ('student_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_results', to='solving_tests.studentresult')),
                ('task_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_tests.taskgroup')),
            ],
            options={
                'unique_together': {('student_result', 'task_group')},
            },
        ),
    ]
