# Generated by Django 5.0.6 on 2025-12-16 20:36

from django.db import migrations
import json
import random


def update_max_points(apps, schema_editor):
    """Обновляем max_points для существующих записей StudentResult"""
    StudentResult = apps.get_model('solving_tests', 'StudentResult')
    AboutTest = apps.get_model('create_tests', 'AboutTest')

    # Импорт функции для рандомизации (упрощённая версия)
    def get_test_max_points(test, student_id, attempt_number):
        # Создаем seed на основе id студента, id теста и номера попытки
        seed = hash(f"{student_id}_{test.id}_{attempt_number}") % (2**32)
        random.seed(seed)

        # Проверяем, использует ли тест новую систему TaskGroup
        task_groups = test.task_groups.all()

        if task_groups.exists():
            # Новая система
            total_points = sum(tg.points_for_solve for tg in task_groups)
        else:
            # Старая система: группируем по block_expression_num
            from collections import defaultdict
            blocks = defaultdict(list)

            for ex in test.expressions.all():
                blocks[ex.block_expression_num].append(ex)

            # Из каждого блока берем points_for_solve первого элемента
            total_points = 0
            for block_num, expressions in blocks.items():
                if expressions:
                    total_points += expressions[0].points_for_solve

        return total_points

    # Обновляем все записи где max_points = 0
    results_to_update = StudentResult.objects.filter(max_points=0)

    for result in results_to_update:
        try:
            max_points = get_test_max_points(result.test, result.student.id, result.attempt_number)
            result.max_points = max_points
            result.save(update_fields=['max_points'])
            print(f"Updated max_points for {result.student.email} - {result.test.name_tests}: {max_points}")
        except Exception as e:
            print(f"Error updating result {result.id}: {e}")


def reverse_update_max_points(apps, schema_editor):
    """Откатываем изменения"""
    StudentResult = apps.get_model('solving_tests', 'StudentResult')
    StudentResult.objects.update(max_points=0)


class Migration(migrations.Migration):

    dependencies = [
        ('solving_tests', '0004_alter_studentresult_options_and_more'),
        ('create_tests', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_max_points, reverse_update_max_points),
    ]
