# Generated by Django 5.0.6 on 2025-12-16 20:41

from django.db import migrations
import random


def fix_max_points(apps, schema_editor):
    """Правильно пересчитываем max_points для всех записей"""
    StudentResult = apps.get_model('solving_tests', 'StudentResult')
    AboutTest = apps.get_model('create_tests', 'AboutTest')

    def get_correct_max_points(test, student_id, attempt_number):
        """Корректный пересчёт максимальных баллов"""
        # Создаем seed на основе id студента, id теста и номера попытки
        seed = hash(f"{student_id}_{test.id}_{attempt_number}") % (2**32)
        random.seed(seed)

        # Проверяем, использует ли тест новую систему TaskGroup
        task_groups = test.task_groups.all()

        if task_groups.exists():
            # Новая система
            total_points = sum(tg.points_for_solve for tg in task_groups)
        else:
            # Старая система: правильно группируем по block_expression_num
            from collections import defaultdict
            blocks = defaultdict(list)

            for ex in test.expressions.all():
                blocks[ex.block_expression_num].append(ex)

            total_points = 0
            for block_num, expressions in blocks.items():
                if expressions:
                    # Выбираем случайное задание из блока (так как это рандомизированный тест)
                    selected_expression = random.choice(expressions)
                    total_points += selected_expression.points_for_solve

        return total_points

    # Пересчитываем для всех записей
    for result in StudentResult.objects.all():
        try:
            correct_max_points = get_correct_max_points(result.test, result.student.id, result.attempt_number)

            # Обновляем только если значение изменилось
            if result.max_points != correct_max_points:
                old_max = result.max_points
                result.max_points = correct_max_points
                result.save(update_fields=['max_points'])
                print(f"Fixed max_points for {result.student.email} - {result.test.name_tests}: {old_max} -> {correct_max_points}")

        except Exception as e:
            print(f"Error fixing result {result.id}: {e}")


def reverse_fix_max_points(apps, schema_editor):
    """Откат"""
    pass  # Не откатываем, так как данные уже были неправильными


class Migration(migrations.Migration):

    dependencies = [
        ('solving_tests', '0005_update_max_points'),
        ('create_tests', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fix_max_points, reverse_fix_max_points),
    ]
