# Generated by Django 5.0.6 on 2025-12-16 20:45

from django.db import migrations
import json


def final_fix_max_points(apps, schema_editor):
    """Исправляем max_points для результатов, которые решались со старой логикой"""
    StudentResult = apps.get_model('solving_tests', 'StudentResult')

    for result in StudentResult.objects.all():
        try:
            # Проверяем количество ответов
            try:
                answers = json.loads(result.res_answer) if result.res_answer else []
            except (json.JSONDecodeError, ValueError):
                try:
                    import ast
                    answers = ast.literal_eval(result.res_answer) if result.res_answer else []
                except (ValueError, SyntaxError):
                    answers = []

            answers_count = len(answers)

            # Если студент отвечал на несколько вопросов, а max_points слишком мал,
            # пересчитаем max_points как сумму всех заданий в блоках
            if answers_count > 1 and result.max_points < result.result_points:

                # Считаем все задания в тесте (старая логика)
                task_groups = result.test.task_groups.all()

                if task_groups.exists():
                    # Новая система - уже правильно
                    total_max_points = sum(tg.points_for_solve for tg in task_groups)
                else:
                    # Старая система - считаем все задания
                    from collections import defaultdict
                    blocks = defaultdict(list)

                    for ex in result.test.expressions.all():
                        blocks[ex.block_expression_num].append(ex)

                    # Для старых результатов считаем ВСЕ задания в каждом блоке
                    total_max_points = 0
                    for expressions in blocks.values():
                        total_max_points += sum(ex.points_for_solve for ex in expressions)

                if total_max_points != result.max_points:
                    old_max = result.max_points
                    result.max_points = total_max_points
                    result.save(update_fields=['max_points'])
                    print(f"Final fix: {result.student.email} - {result.test.name_tests}: {old_max} -> {total_max_points} (answers: {answers_count})")

        except Exception as e:
            print(f"Error in final fix for result {result.id}: {e}")


def reverse_final_fix(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('solving_tests', '0006_fix_max_points'),
        ('create_tests', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(final_fix_max_points, reverse_final_fix),
    ]
